force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class_ID__c.field-meta.xml
<CustomField>
    <fullName>Class_ID__c</fullName>
    <label>Class ID</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassRace__c/ClassRace__c.object-meta.xml
<CustomObject>
    <label>ClassRace</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>ClassRace Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ClassRaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassRace__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>ClassRaces</relationshipLabel>
    <relationshipName>ClassRaces</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassRace__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>ClassRaces</relationshipLabel>
    <relationshipName>ClassRaces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WoWPlayableRaceClassCombinationTest.cls
@isTest
public class WoWPlayableRaceClassCombinationTest {
    @isTest
    static void testCreateCombinations() {
        insert new Class__c(Name = 'Warrior', Class_ID__c = 1);
        insert new Race__c(Name = 'Orc');
        
        String mockBody = '{"playable_races": [{"id": 1, "name": "Orc"}]}';
        Test.setMock(HttpCalloutMock.class, new UtilityMethodsMock(200, 'OK', mockBody, new Map<String, String>()));
        
        Test.startTest();
        WoWPlayableRaceClassCombination.createRaceClassCombinations();
        Test.stopTest();
        
        System.assert([SELECT Id FROM ClassRace__c].size() > 0);
    }
}