force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class_ID__c.field-meta.xml
<CustomField>
    <fullName>Class_ID__c</fullName>
    <label>Class ID</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specialization__c/Specialization__c.object-meta.xml
<CustomObject>
    <label>Specialization</label>
    <nameField>
        <label>Specialization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialization__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Specializations</relationshipLabel>
    <relationshipName>Specializations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WoWPlayableClasses.cls
public with sharing class WoWPlayableClasses {
    
    public static void createPlayableClasses(){

        String getClassIndex = WoWDataAPI.fetchPlayableClassIndex();
        ClassesIndexObject classesIndex = (ClassesIndexObject) JSON.deserialize(getClassIndex.replaceAll('_links', 'links'), ClassesIndexObject.class);

        List<Class__c> classes = new List<Class__c>();
        for(ClassesIndexObject.classes c : classesIndex.classes){
            classes.add(new Class__c(Name=c.name, Class_ID__c=c.id));
        }

        try{
            if(Schema.sObjectType.Class__c.isCreateable()
            && Schema.sObjectType.Class__c.isUpdateable()){
                upsert classes;
            }
        } catch(DmlException e) {
            System.debug('The following exception has occurred when trying to upsert a Character Class: ' + e.getMessage());
        }
    }

    public static void createPlayableClassSpecs(){
        
        List<Class__c> playableClasses = [SELECT Id, Name, Class_ID__c FROM Class__c];

        List<Specialization__c> specialization = new List<Specialization__c>();
        for(Class__c c : playableClasses){
            String getClass = WoWDataAPI.fetchPlayableClass(c.Class_ID__c);
            ClassObject playableClass = (ClassObject) JSON.deserialize(getClass.replaceAll('_links', 'links'), ClassObject.class);

            for(ClassObject.specializations spec : playableClass.specializations){
                specialization.add(new Specialization__c(Name=spec.name, Class__c=c.Id));
            }
        }

        try{
            if(Schema.sObjectType.Specialization__c.isCreateable()
             && Schema.sObjectType.Specialization__c.isUpdateable()){
                upsert specialization;
            }
        } catch(DmlException e) {
            System.debug('The following exception has occurred when trying to upsert a Specialization: ' + e.getMessage());
        }
    }
}