force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Realm__c/Realm__c.object-meta.xml
<CustomObject>
    <description>World of Warcraft Realms</description>
    <label>Realm</label>
    <nameField>
        <label>Realm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Realm__c/fields/Realm_Slug__c.field-meta.xml
<CustomField>
    <fullName>Realm_Slug__c</fullName>
    <label>Realm Slug</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resilient_Communication_Device__c/Resilient_Communication_Device__c.object-meta.xml
<CustomObject>
    <label>ESCC Communication Device</label>
    <nameField>
        <label>Resilient Communication Device Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ESCC Communication Devices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resilient_Communication_Device__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>ESCC Communication Devices</relationshipLabel>
    <relationshipName>ESCC_Communication_Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resilient_Communication_Device__c/fields/Device_Level__c.field-meta.xml
<CustomField>
    <fullName>Device_Level__c</fullName>
    <label>Device Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Contingency</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resilient_Communication_Device__c/fields/Device_Number__c.field-meta.xml
<CustomField>
    <fullName>Device_Number__c</fullName>
    <label>Device Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Resilient_Communication_Device__c/fields/Device_Type__c.field-meta.xml
<CustomField>
    <fullName>Device_Type__c</fullName>
    <label>Device Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cellular</fullName>
            </value>
            <value>
                <fullName>GETS</fullName>
            </value>
            <value>
                <fullName>Landline</fullName>
            </value>
            <value>
                <fullName>Satellite</fullName>
            </value>
            <value>
                <fullName>VoIP</fullName>
            </value>
            <value>
                <fullName>WPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resilient_Communication_Device__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ESCC Communication Devices</relationshipLabel>
    <relationshipName>ESCC_Communication_Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specialization__c/Specialization__c.object-meta.xml
<CustomObject>
    <label>Specialization</label>
    <nameField>
        <label>Specialization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialization__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Specializations</relationshipLabel>
    <relationshipName>Specializations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static void createWoWMetadata() {
        Class__c cls = new Class__c(Name = 'Warrior');
        insert cls;
        
        Specialization__c spec = new Specialization__c(Name = 'Arms', Class__c = cls.Id);
        insert spec;
        
        Realm__c realm = new Realm__c(Name = 'Aegwynn', Realm_Slug__c = 'aegwynn');
        insert realm;
        
        Race__c race = new Race__c(Name = 'Orc');
        insert race;
    }

    public static List<Account> createAccounts(Integer num) {
        List<Account> accs = new List<Account>();
        for(Integer i=0; i<num; i++) {
            accs.add(new Account(Name = 'Test Acc ' + i));
        }
        insert accs;
        return accs;
    }

    public static List<Contact> createContacts(Id accId, Integer num) {
        List<Contact> cons = new List<Contact>();
        for(Integer i=0; i<num; i++) {
            cons.add(new Contact(LastName = 'Contact ' + i, AccountId = accId));
        }
        insert cons;
        return cons;
    }

    public static List<Resilient_Communication_Device__c> createDevices(Id accId, Id conId, Integer num) {
        List<Resilient_Communication_Device__c> devs = new List<Resilient_Communication_Device__c>();
        for(Integer i=0; i<num; i++) {
            devs.add(new Resilient_Communication_Device__c(
                Organization__c = accId,
                Contact__c = conId,
                Device_Type__c = 'Satellite',
                Device_Level__c = 'Primary',
                Device_Number__c = '12345' + i
            ));
        }
        insert devs;
        return devs;
    }
}