force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class_ID__c.field-meta.xml
<CustomField>
    <fullName>Class_ID__c</fullName>
    <label>Class ID</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClassRace__c/ClassRace__c.object-meta.xml
<CustomObject>
    <label>ClassRace</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>ClassRace Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ClassRaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClassRace__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>ClassRaces</relationshipLabel>
    <relationshipName>ClassRaces</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClassRace__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>ClassRaces</relationshipLabel>
    <relationshipName>ClassRaces</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/WoWPlayableRaceClassCombination.cls
public with sharing class WoWPlayableRaceClassCombination {

    public static void createRaceClassCombinations() {
        List<Class__c> playableClasses = [SELECT Id, Name, Class_ID__c FROM Class__c];
        List<Race__c> playableRaces = [SELECT Id, Name FROM Race__c];

        List<ClassRace__c> raceClasses = new List<ClassRace__c>();
        for(Class__c c : playableClasses){

            String getClass = WoWDataAPI.fetchPlayableClass(c.Class_ID__c);
            ClassObject playableClass = (ClassObject) JSON.deserialize(getClass.replaceAll('_links', 'links'), ClassObject.class);

            for(ClassObject.playable_races race : playableClass.playable_races){
                
                Race__c playableRaceRecord;
                for(Race__c raceRecord : playableRaces){
                    if(raceRecord.Name == race.name){
                        playableRaceRecord = raceRecord;
                    }
                }
                raceClasses.add(new ClassRace__c(Class__c=c.Id, Race__c=playableRaceRecord.Id));
            }
        }

        try{
            if(Schema.sObjectType.ClassRace__c.isCreateable()
            && Schema.sObjectType.ClassRace__c.isUpdateable()){
                upsert raceClasses;
            }
        } catch(DmlException e) {
            System.debug('The following exception has occurred when trying to upsert a ClassRace Combination: ' + e.getMessage());
        }
    }
}