force-app/main/default/objects/Realm__c/Realm__c.object-meta.xml
<CustomObject>
    <description>World of Warcraft Realms</description>
    <label>Realm</label>
    <nameField>
        <label>Realm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Realm__c/fields/Realm_ID__c.field-meta.xml
<CustomField>
    <fullName>Realm_ID__c</fullName>
    <label>Realm ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Realm__c/fields/Realm_Slug__c.field-meta.xml
<CustomField>
    <fullName>Realm_Slug__c</fullName>
    <label>Realm Slug</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WoWRealms.cls
public with sharing class WoWRealms {

    public static void createAllRealms() {

        String getRealms = WoWProfileAPI.fetchRealmIndex();
        RealmIndexObject realmIndex = (RealmIndexObject) JSON.deserialize(getRealms.replaceAll('_links', 'links'), RealmIndexObject.class);
        
        List<Realm__c> realms = new List<Realm__c>();
        for(RealmIndexObject.realms realm : realmIndex.realms){
            realms.add(new Realm__c(Realm_ID__c=realm.id, Name=realm.name, Realm_Slug__c=realm.slug));
        }

        try{
            if(Schema.sObjectType.Realm__c.isCreateable()
            && Schema.sObjectType.Realm__c.isUpdateable()){
                upsert realms;
            }
        } catch(DmlException e){
            System.debug('The following exception has occurred when trying to upsert Realms: ' + e.getMessage());
        }
    }
}