force-app/main/default/objects/KrakenDataTableConfig__c/KrakenDataTableConfig__c.object-meta.xml
<CustomObject>
    <label>Kraken Data Table Config</label>
    <nameField>
        <displayFormat>CONFIG-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kraken Data Table Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KrakenDataTableConfig__c/fields/DisplayName__c.field-meta.xml
<CustomField>
    <fullName>DisplayName__c</fullName>
    <label>Display Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/KrakenDataTableConfigSelector.cls
public with sharing class KrakenDataTableConfigSelector extends VisualEditor.DynamicPickList {
    public override VisualEditor.DataRow getDefaultValue() {
        return null;
    }

    public override VisualEditor.DynamicPickListRows getValues() {
        VisualEditor.DynamicPickListRows configOptions = new VisualEditor.DynamicPickListRows();
        List<KrakenDataTableConfig__c> configs = [SELECT Id, DisplayName__c FROM KrakenDataTableConfig__c ORDER BY DisplayName__c ASC];
        for (KrakenDataTableConfig__c config : configs) {
            configOptions.addRow(new VisualEditor.DataRow(config.DisplayName__c, config.Id));
        }
        return configOptions;
    }
}