force-app/main/default/objects/Character_Model__c/Character_Model__c.object-meta.xml
<CustomObject>
    <label>Character Model</label>
    <nameField>
        <label>Character Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Character Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Character_Model__c/fields/Avatar__c.field-meta.xml
<CustomField>
    <fullName>Avatar__c</fullName>
    <label>Avatar</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Back__c.field-meta.xml
<CustomField>
    <fullName>Back__c</fullName>
    <label>Back</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Character_ID__c.field-meta.xml
<CustomField>
    <fullName>Character_ID__c</fullName>
    <externalId>true</externalId>
    <label>Character ID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Chest__c.field-meta.xml
<CustomField>
    <fullName>Chest__c</fullName>
    <label>Chest</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Feet__c.field-meta.xml
<CustomField>
    <fullName>Feet__c</fullName>
    <label>Feet</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Finger_2__c.field-meta.xml
<CustomField>
    <fullName>Finger_2__c</fullName>
    <label>Secondary Ring</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Finger__c.field-meta.xml
<CustomField>
    <fullName>Finger__c</fullName>
    <label>Primary Ring</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Hands__c.field-meta.xml
<CustomField>
    <fullName>Hands__c</fullName>
    <label>Hands</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Head__c.field-meta.xml
<CustomField>
    <fullName>Head__c</fullName>
    <label>Head</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Inset__c.field-meta.xml
<CustomField>
    <fullName>Inset__c</fullName>
    <label>Inset</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Legs__c.field-meta.xml
<CustomField>
    <fullName>Legs__c</fullName>
    <label>Legs</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Main_Hand__c.field-meta.xml
<CustomField>
    <fullName>Main_Hand__c</fullName>
    <label>Main Hand</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Main_Raw__c.field-meta.xml
<CustomField>
    <fullName>Main_Raw__c</fullName>
    <label>Main Raw</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Neck__c.field-meta.xml
<CustomField>
    <fullName>Neck__c</fullName>
    <label>Neck</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Off_Hand__c.field-meta.xml
<CustomField>
    <fullName>Off_Hand__c</fullName>
    <label>Off Hand</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Realm__c.field-meta.xml
<CustomField>
    <fullName>Realm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Realm</label>
    <referenceTo>Realm__c</referenceTo>
    <relationshipLabel>Character Models</relationshipLabel>
    <relationshipName>Character_Models</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Shoulders__c.field-meta.xml
<CustomField>
    <fullName>Shoulders__c</fullName>
    <label>Shoulders</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Tabard__c.field-meta.xml
<CustomField>
    <fullName>Tabard__c</fullName>
    <label>Tabard</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Trinket_1__c.field-meta.xml
<CustomField>
    <fullName>Trinket_1__c</fullName>
    <label>Primary Trinket</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Trinket_2__c.field-meta.xml
<CustomField>
    <fullName>Trinket_2__c</fullName>
    <label>Secondary Trinket</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Waist__c.field-meta.xml
<CustomField>
    <fullName>Waist__c</fullName>
    <label>Waist</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Character_Model__c/fields/Wrist__c.field-meta.xml
<CustomField>
    <fullName>Wrist__c</fullName>
    <label>Wrist</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Guild_Applicant__c/Guild_Applicant__c.object-meta.xml
<CustomObject>
    <label>Guild Applicant</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guild Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Guild_Applicant__c/fields/Character_Model__c.field-meta.xml
<CustomField>
    <fullName>Character_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Character Model</label>
    <referenceTo>Character_Model__c</referenceTo>
    <relationshipLabel>Guild Applicants</relationshipLabel>
    <relationshipName>Guild_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guild_Applicant__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Guild Applicants</relationshipLabel>
    <relationshipName>Guild_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guild_Applicant__c/fields/Main_Spec__c.field-meta.xml
<CustomField>
    <fullName>Main_Spec__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Spec</label>
    <referenceTo>Specialization__c</referenceTo>
    <relationshipLabel>Guild Applicants</relationshipLabel>
    <relationshipName>Guild_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guild_Applicant__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Guild Applicants</relationshipLabel>
    <relationshipName>Guild_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guild_Applicant__c/fields/Realm__c.field-meta.xml
<CustomField>
    <fullName>Realm__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Realm</label>
    <referenceTo>Realm__c</referenceTo>
    <relationshipLabel>Guild Applicants</relationshipLabel>
    <relationshipName>Guild_Applicants</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Realm__c/Realm__c.object-meta.xml
<CustomObject>
    <description>World of Warcraft Realms</description>
    <label>Realm</label>
    <nameField>
        <label>Realm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Realm__c/fields/Realm_Slug__c.field-meta.xml
<CustomField>
    <fullName>Realm_Slug__c</fullName>
    <label>Realm Slug</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Specialization__c/Specialization__c.object-meta.xml
<CustomObject>
    <label>Specialization</label>
    <nameField>
        <label>Specialization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialization__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Specializations</relationshipLabel>
    <relationshipName>Specializations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WoWCharacter.cls
public with sharing class WoWCharacter {

    public static void createCharacterLead(String realmSlug, String characterName) {

        String characterProfile = WoWProfileAPI.fetchCharacterProfileSummary(realmSlug, characterName);
        CharacterProfileSummaryObject characterProfileObject = (CharacterProfileSummaryObject) JSON.deserialize(characterProfile.replaceAll('_links', 'links'), CharacterProfileSummaryObject.class);
        
        Id classId = [SELECT Id FROM Class__c WHERE Name =: characterProfileObject.character_class.name.en_US LIMIT 1].Id;
        Id specId = [SELECT Id FROM Specialization__c WHERE Class__c =: classId AND Name =: characterProfileObject.active_spec.name.en_US LIMIT 1].Id;
        Id realmId = [SELECT Id FROM Realm__c WHERE Name =: characterProfileObject.realm.name.en_US LIMIT 1].Id;
        Id raceId = [SELECT Id FROM Race__c WHERE Name =: characterProfileObject.race.name.en_US.escapeJava() LIMIT 1].Id;

        Lead characterLead = new Lead(
            LastName=characterName.capitalize(),
            Company='WoW API',
            Realm__c=realmId,
            Faction__c=characterProfileObject.faction.name.en_US,
            Class__c=classId,
            Main_Spec__c=SpecId,
            Level__c=characterProfileObject.level,
            Item_Level__c=characterProfileObject.equipped_item_level,
            Race__c=raceId
        );

        try{
            if(Schema.SObjectType.Lead.isCreateable()
            && Schema.SObjectType.Lead.isUpdateable()){
                upsert characterLead;
            }
        } catch (DmlException e) {
            System.debug('The following exception has occurred when trying to upsert a Character Lead: ' + e.getMessage());
        }
    }

    // public static void createCharacterApplicant(Id realmId, String characterName) {

    //     String realmSlug = [SELECT Id, Realm_Slug__c FROM Realm__c WHERE Id =: realmId].Realm_Slug__c;
    //     characterName = characterName.toLowerCase();

    //     String characterProfile = WoWProfileAPI.fetchCharacterProfileSummary(realmSlug, characterName);
    //     CharacterProfileSummaryObject characterProfileObject = (CharacterProfileSummaryObject) JSON.deserialize(characterProfile.replaceAll('_links', 'links'), CharacterProfileSummaryObject.class);

    //     Id classId = [SELECT Id FROM Class__c WHERE Name =: characterProfileObject.character_class.name.en_US LIMIT 1].Id;
    //     Id specId = [SELECT Id FROM Specialization__c WHERE Class__c =: classId AND Name =: characterProfileObject.active_spec.name.en_US LIMIT 1].Id;
    //     Id raceId = [SELECT Id FROM Race__c WHERE Name =: characterProfileObject.race.name.en_US.escapeJava() LIMIT 1].Id;

    //     Guild_Applicant__c characterApplicant = new Guild_Applicant__c(
    //         Name=characterName.capitalize(),
    //         Realm__c=realmId,
    //         Faction__c=characterProfileObject.faction.name.en_US,
    //         Class__c=classId,
    //         Main_Spec__c=SpecId,
    //         Level__c=characterProfileObject.level,
    //         Item_Level__c=characterProfileObject.equipped_item_level,
    //         Race__c=raceId,
    //         Title__c=characterProfileObject.active_title.name.en_US
    //     );

    //     try{
    //         if(Schema.SObjectType.Lead.isCreateable()
    //         && Schema.SObjectType.Lead.isUpdateable()){
    //             upsert characterApplicant;
    //         }
    //     } catch (DmlException e) {
    //         System.debug('The following exception has occurred when trying to upsert a Character Lead: ' + e.getMessage());
    //     }
    // }

    @InvocableMethod(Label='Wow Character' Description='Creates a new Character Lead from the WoW Profile API')
    public static List<SObject> createCharacterApplicant(List<List<String>> args){

        String realmSlug = args[0][0];
        String characterName = args[0][1].toLowerCase();
        String recordId = args[0][2];

        String characterProfile = WoWProfileAPI.fetchCharacterProfileSummary(realmSlug, characterName);
        CharacterProfileSummaryObject characterProfileObject = (CharacterProfileSummaryObject) JSON.deserialize(characterProfile.replaceAll('_links', 'links'), CharacterProfileSummaryObject.class);

        Id classId = [SELECT Id FROM Class__c WHERE Name =: characterProfileObject.character_class.name.en_US LIMIT 1].Id;
        Id specId = [SELECT Id FROM Specialization__c WHERE Class__c =: classId AND Name =: characterProfileObject.active_spec.name.en_US LIMIT 1].Id;
        Id realmId = [SELECT Id FROM Realm__c WHERE Name =: characterProfileObject.realm.name.en_US LIMIT 1].Id;
        Id raceId = [SELECT Id FROM Race__c WHERE Name =: characterProfileObject.race.name.en_US.escapeJava() LIMIT 1].Id;

        Character_Model__c characterModel = createCharacterModel(realmSlug, characterName, characterProfileObject.id);

        List<SObject> guildApplicant = new List<SObject>();
        SObject characterApplicant = new Guild_Applicant__c(
            Id=recordId,
            Character_ID__c=characterProfileObject.id,
            Name=characterName.capitalize(),
            Realm__c=realmId,
            Faction__c=characterProfileObject.faction.name.en_US,
            Class__c=classId,
            Main_Spec__c=SpecId,
            Level__c=characterProfileObject.level,
            Item_Level__c=characterProfileObject.equipped_item_level,
            Race__c=raceId,
            Title__c=characterProfileObject.active_title.name.en_US,
            Character_Model__c=characterModel.Id
        );

        guildApplicant.add(characterApplicant);

        System.debug(guildApplicant);

        return guildApplicant;
    }

    public static Character_Model__c createCharacterModel(String realmSlug, String characterName, Integer externalId) {

        String characterMedia = WoWProfileAPI.fetchCharacterMediaSummary(realmSlug, characterName);
        String characterEquipment = WoWProfileAPI.fetchCharacterEquipmentSummary(realmSlug, characterName);

        CharacterMediaSummaryObject characterMediaObject = (CharacterMediaSummaryObject) JSON.deserialize(characterMedia.replaceAll('_links', 'links'), CharacterMediaSummaryObject.class);
        CharacterEquipmentSummaryObject characterEquipmentObject = (CharacterEquipmentSummaryObject) JSON.deserialize(characterEquipment.replaceAll('set', 'set_bonus').replaceAll('_links', 'links').replaceAll('links', 'links_extra'), CharacterEquipmentSummaryObject.class);

        Map<String,String> itemMap = mapItemNameToURL(characterEquipmentObject);

        Character_Model__c characterModel = new Character_Model__c(
            Character_ID__c=externalId,
            Name=characterName.capitalize(),
            Avatar__c=characterMediaObject.assets[0].value,
            Inset__c=characterMediaObject.assets[1].value,
            Main_Raw__c=characterMediaObject.assets[2].value,
            Head__c=itemMap.get('Head'),
            Neck__c=itemMap.get('Neck'),
            Shoulders__c=itemMap.get('Shoulders'),
            Chest__c=itemMap.get('Chest'),
            Waist__c=itemMap.get('Waist'),
            Legs__c=itemMap.get('Legs'),
            Feet__c=itemMap.get('Feet'),
            Wrist__c=itemMap.get('Wrist'),
            Hands__c=itemMap.get('Hands'),
            Finger__c=itemMap.get('Finger'),
            Finger_2__c=itemMap.get('Finger_2'),
            Trinket_1__c=itemMap.get('Trinket_1'),
            Trinket_2__c=itemMap.get('Trinket_2'),
            Back__c=itemMap.get('Back'),
            Main_Hand__c=itemMap.get('Main_Hand'),
            Off_Hand__c=itemMap.get('Off_Hand'),
            Tabard__c=itemMap.get('Tabard')
        );

        try{
            if(Schema.SObjectType.Character_Model__c.isCreateable()
            && Schema.SObjectType.Character_Model__c.isUpdateable()){
                upsert characterModel;
            }
        } catch (DmlException e) {
            System.debug('The following exception has occurred when trying to upsert a Character Model: ' + e.getMessage());
        }
        
        return characterModel;
    }

    public static Map<String,String> mapItemNameToURL(CharacterEquipmentSummaryObject characterEquipmentObject){
        Map<String,String> itemMap = new Map<String,String>();
        for(CharacterEquipmentSummaryObject.equipped_items item : characterEquipmentObject.equipped_items){
            switch on item.slot.name {
                when 'Head' {
                    itemMap.put('Head', getItemMediaURL(item.item.id));
                }
                when 'Neck' {
                    itemMap.put('Neck', getItemMediaURL(item.item.id));
                }
                when 'Shoulders' {
                    itemMap.put('Shoulders', getItemMediaURL(item.item.id));
                }
                when 'Chest' {
                    itemMap.put('Chest', getItemMediaURL(item.item.id));
                }
                when 'Waist' {
                    itemMap.put('Waist', getItemMediaURL(item.item.id));
                }
                when 'Legs' {
                    itemMap.put('Legs', getItemMediaURL(item.item.id));
                }
                when 'Feet' {
                    itemMap.put('Feet', getItemMediaURL(item.item.id));
                }
                when 'Wrist' {
                    itemMap.put('Wrist', getItemMediaURL(item.item.id));
                }
                when 'Hands' {
                    itemMap.put('Hands', getItemMediaURL(item.item.id));
                }
                when 'Ring 1' {
                    itemMap.put('Finger', getItemMediaURL(item.item.id));
                }
                when 'Ring 2' {
                    itemMap.put('Finger_2', getItemMediaURL(item.item.id));
                }
                when 'Trinket 1' {
                    itemMap.put('Trinket_1', getItemMediaURL(item.item.id));
                }
                when 'Trinket 2' {
                    itemMap.put('Trinket_2', getItemMediaURL(item.item.id));
                }
                when 'Back' {
                    itemMap.put('Back', getItemMediaURL(item.item.id));
                }
                when 'Main Hand' {
                    itemMap.put('Main_Hand', getItemMediaURL(item.item.id));
                }
                when 'Off Hand' {
                    itemMap.put('Off_Hand', getItemMediaURL(item.item.id));
                }
                when 'Tabard'{
                    itemMap.put('Tabard', getItemMediaURL(item.item.id));
                }
            }
        }

        return itemMap;
    }

    public static String getItemMediaURL(Integer itemId){
        
        String itemMedia = WoWDataAPI.fetchItemMedia(itemId);
        ItemMediaObject itemObject = (ItemMediaObject) JSON.deserialize(itemMedia.replaceAll('_links', 'links'), ItemMediaObject.class);

        return itemObject.assets[0].value;
    }
}